# Generated by Django 5.2 on 2025-05-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="место, в котором необходимо выполнять привычку",
                        max_length=50,
                        null=True,
                        verbose_name="место выполнения привычки",
                    ),
                ),
                (
                    "time_action",
                    models.TimeField(
                        blank=True,
                        default=None,
                        help_text="время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="время выполнения привычки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        default="1,2,3,4,5,6,7",
                        help_text="дни недели через запятую 1,2,3,4,5,6,7",
                        max_length=50,
                        verbose_name="день недели, когда необходимо выполнять привычку",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="действие, которое представляет собой привычка.",
                        max_length=50,
                        null=True,
                        verbose_name="действие-привычка",
                    ),
                ),
                (
                    "nice",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="вознаграждение",
                        max_length=50,
                        null=True,
                        verbose_name="чем пользователь должен себя вознаградить",
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="время на выполнение привычки в секундах",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        verbose_name="привычки можно публиковать в общий доступ",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_related",
                        to="habit_tracker.habit",
                        verbose_name="ссылка на полезную привычку",
                    ),
                ),
            ],
        ),
    ]
