# Generated by Django 5.2 on 2025-04-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_alter_habit_related"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="pablic",
            new_name="public",
        ),
        migrations.AlterField(
            model_name="habit",
            name="related",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_related",
                to="habit_tracker.habit",
                verbose_name="ссылка на полезную привычку",
            ),
        ),
    ]
