# Generated by Django 5.2 on 2025-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_remove_habit_day_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="время на выполнение привычки в секундах",
            ),
        ),
    ]
