# Generated by Django 5.2 on 2025-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_api_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_telegram',
            field=models.CharField(blank=True, default=None, help_text='Telegram_ID для бота рассылки', max_length=50, null=True, verbose_name='Telegram_ID пользователя'),
        ),
    ]
