# Generated by Django 5.2 on 2025-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_api_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='api_telegram',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nick_telegram',
            field=models.CharField(blank=True, default=None, help_text='Telegram ник для бота рассылки', max_length=50, null=True, verbose_name='Telegram ник пользователя'),
        ),
    ]
