name: Django CI/CD Pipeline
on: [push, pull_request]
jobs:

 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Copy project files to server
      run: |
        rsync -avz . user_n@158.160.28.176:/home/user_n/tracker
    

            
        

