name: Django CI/CD Pipeline
on: [push, pull_request]
jobs:

 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Copy project files to server
      run: |
        rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
        
        

