name: Django CI/CD Pipeline
on: [push, pull_request]
jobs:

 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: SSH
      run: |
        ssh -o StrictHostKeyChecking=no user_n@130.193.52.164 << 'EOF'
          cd ${{ secrets.DEPLOY_DIR }}
        EOF
    - name: test
      run: ls $GITHUB_WORKSPACE
    - name: Copy project files to server
      run: |
        rsync -avz $GITHUB_WORKSPACE/README.md user_n@130.193.52.164:/home/user_n/tracker/
        

