name: Django CI/CD Pipeline
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Pull docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_APP }}:${{ secrets.DOCKER_APP_ID }}
          docker stop ${{ secrets.DOCKER_APP_ID }} || true
          docker rm ${{ secrets.DOCKER_APP_ID }} || true
          docker run -d --name name_project -p 8000:80 ${{ secrets.DOCKER_APP }}:${{ secrets.DOCKER_APP_ID }} 

        EOF



        